### PR TITLE
Adaptive branch layout

### PR DESCRIPTION
**Pull request by Laguna1**

### CODE REVIEW

**Comment by Laguna1** [comment]
My task in this project was to build a replica of the news site Newsweek.com using the Bootstrap4 framework.
Please check my code, I will be glad to hear your opinion about this work.
Please tell me if something needs to be fixed.
Thanks!

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Laguna1 
### Nice work you have done so far :clap: However, you have a fixes to make before your application can be approved.
- Implement the navigation as from the original design, make it go full width and evenly spaced
menu
- On more stories, there is unnecessary left space after the content. Fix this to look like the original design
more stories space left
- Also, fix your footer to like the original design
footer
- On mobile devices, make images go full width, also redesign the footer and the header to look like the original design
fix navigation
mobile footer 1
mobile footer 2
- On medium devices, your images are not going full width and also you need to adjust your margin to between the images and text to resemble the original design
images go full width
medium screen
### Make all these changes and resubmit for another code review. Good luck.
- Contact me on slack for any clarification @iamraymond
- Happy coding!

**Comment by Laguna1** [comment]
I tried to correct all the comments, I hope that now everything is fine.

**Comment by uryelah** [comment]
Hello **Oksana Petrova**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Good job implementing most of the last TSE feedback, also you did great with writing semantic HTML🎇**

This project requires you to be even more attentive to detail as most of the positioning, spacing, and responsiveness are handled by bootstrap.

There are still some issues you need to work through so hang in there 💪 

---------    

## Required changes 🛠 
---------

### Navbar
- [ ] Make sure there is no margin between the navbar and the body of the page
- [ ] The logo and the navbar must have the same shade of red in their background. Make sure the logo has either a transparent background or the same shade of red for its background.
- [ ] Your navbar is missing the weather info and icon, make sure to include it to make it equal to the original one
- [ ] On wide screens the second row of the navbar has a white background, same for the 'subscribe' background. If you are not sure about the color of a page element, check the CSS in the inspector or use a tool like a[ color picker.](https://developer.mozilla.org/en-US/docs/Tools/Eyedropper)
Screenshot_2020-03-30 NEWSWEEK CLONE
Screenshot_2020-03-30 Newsweek
---

**Medium screens**
- [ ] Make sure you change the height of the navbar on window resize. Compare your and the original below.
Screenshot_2020-03-30 NEWSWEEK CLONE(1)
Screenshot_2020-03-30 Newsweek(1)

---

**Small screens**
- [ ] The font of the nav buttons should not change on resize, make sure you are not using percentages for your font size.
Screenshot_2020-03-30 NEWSWEEK CLONE(2)
Screenshot_2020-03-30 Newsweek(2)

------

### Sections

- [ ] Make sure you add all the headers for all the sections, currently 'Featured stories' is missing its header.
- [ ] Pay attention to the padding around the text over the images. This can be done with Bootstrap classes.
Screenshot_2020-03-30 NEWSWEEK CLONE(3)
Screenshot_2020-03-30 Newsweek(3)

----

- [ ] Compare your 'Debate' section and the original one. Make sure the colors, weights, and style are as close as they can be.
Screenshot_2020-03-30 NEWSWEEK CLONE(4)
Screenshot_2020-03-30 Newsweek(4)

----

- [ ] Pay attention to font-weight on all of the article titles and contents. Make sure it's similar to the original ones:
Screenshot_2020-03-30 Newsweek(5)
Screenshot_2020-03-30 NEWSWEEK CLONE(5)

----

- [ ] Good job adding the scroll to the main sections, but keep in mind that the reason for it is to make sure the sections align horizontally at the bottom before 'In the Magazine'. Make sure there is no extra empty space in the middle section.

- [ ] Keep the scroll but hide the scrollbars. Tip: you have to hide the scroll bar in different ways for different browsers.
Screenshot_2020-03-30 NEWSWEEK CLONE(6)
Screenshot_2020-03-30 Newsweek(6)

----

- [ ] Pay close attention to styling the section titles:
Screenshot_2020-03-30 Newsweek(7)
Screenshot_2020-03-30 NEWSWEEK CLONE(7)

---

- [ ] Make sure the 'Newsletter' image is not distorted and keeps it's proportions:
Screenshot_2020-03-30 Newsweek(8)
Screenshot_2020-03-30 NEWSWEEK CLONE(8)

---

- [x] Remember to resize the footer logo too.
Screenshot_2020-03-30 NEWSWEEK CLONE(9)
Screenshot_2020-03-30 Newsweek(9)


----

### Medium and Small Sizes

- [ ] Make sure the articles are taking a similar proportion of the width in small pages, take care so they don't have extra padding or margin.
- [ ] Make sure your breakpoints are closer to the ones in the original page, you can use your browser responsive development tools to check for the exact page breakpoint.

- [ ] Take extra care of the logo and icons size in the footer:
Screenshot_2020-03-30 NEWSWEEK CLONE(10)
Screenshot_2020-03-30 Newsweek(10)
----

- [ ] Make sure to check your clone in multiple sizes so that there is no text overflow issue like the one below on resize
Screenshot_2020-03-30 NEWSWEEK CLONE(11)
:

----------

I know this project is especially long but take some time to revisit [https://www.newsweek.com/](https://www.newsweek.com/) and to make sure your page looks the same in all the breaking points. You already did the hardest part, you got this!

**Kindly fix the REQUIRED issues and send another code review request.**
 
Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Laguna1** [comment]
To work on this project, I used the requirements from the Microverse Passwright https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/65938290/ 
- where were the main requirements for the project -
  https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap
When working on this project, a cross-browser layout was not used.
The project is adapted only for the Google Chrome browser.

**Comment by lekegitrepo** [comment]
### Hi @Laguna1 :clap: :clap: 
### well done. You still need to consider some of the previous review requirements as mentioned by the TSE:

**_1.  Make sure there is no margin between the navbar and the body of the page. There is a margin on the left side of the page between the page and navbar_**

**_2. Make sure you change the height of the navbar on window resize. Compare your and the original._**

**_3. The font of the nav buttons should not change on resize, make sure you are not using percentages for your font size._**

**_4. Compare your 'Debate' section and the original one. Make sure the colors, weights, and styles are as close as they can be._**

**_5. Keep the scroll but hide the scrollbars. Tip: you have to hide the scroll bar in different ways for different browsers._**

**_6. Remember to resize the footer logo too._**

**_These are some of the previous review requirements missing on the page. For details please check the previous review instructions._**

### Reviewed by: _Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes.

**Comment by davidmrtz-dev** [comment]
## Hi @Laguna1  . 👨‍🚀  
### Very good job so far. You correctly implemented the changes required by the TSE's.
However, there's a couple of issues need to be implemented/fixed to improve your project and make it looks awesome!  👨‍💻  ⬇️ 
Based on the requirements of this project :
**In this project students are asked to be more precise and to make sure that their page looks exactly the same as the source page.**
Kindly please check the comments below and make the changes required.
****

- [x] Sign up for newsletter on 'lg' size.
There's an issue on 'lg' size (based on the predefined sizes of bootstrap more info [here](https://www.w3schools.com/bootstrap/bootstrap_grid_system.asp)).
Please fix the positioning so that the elements do not overlap with each other.

Screen Shot 2020-03-31 at 11 57 06 PM

****

- [x] Titles of sections.
Please add bottom padding or margin to give the titles a little space in the bottom part of the title.
Reference images below.

How it looks now. ⬇️ 

Screen Shot 2020-04-01 at 12 01 03 AM

The example on which the project is based. ⬇️ 

Screen Shot 2020-04-01 at 12 01 15 AM

****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  


**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Comment by Laguna1** [comment]
Done! What do you say this time?

**Comment by Dandush03** [comment]
### :heavy_check_mark: Project Approve :exploding_head: :checkered_flag:
# Hey @Laguna1  :wave: 
### Great Job so Far :grey_exclamation: :grey_exclamation: :muscle: :smiley: 

### Following Previous Reviews and Seeing you Have Made Required Changes. 
### The project Looks Great.:grey_exclamation::wink:.

###### Please hide does scroll bar. they are not par as a requirement of this project but it makes your project look bad. BTW, may you would like to check what does sticky position do and apply it to this project. 
 > if you need any help, let me know through slack

### Good Luck in your Next Assignment
### Happy coding:computer: 
#### Daniel Laloush

**Pull request merged**
